#!/usr/bin/env python2.7

'''
/*
 * The Shadow Simulator
 * Copyright (c) 2010-2011, Rob Jansen
 * See LICENSE for licensing information
 */
'''

import sys, os, argparse, subprocess, multiprocessing, shlex, shutil, urllib2, tarfile, gzip, stat, time
from datetime import datetime

import logging
logging.basicConfig(format='%(asctime)s %(levelname)s %(message)s', level=logging.DEBUG)

BUILD_PREFIX="./build"
INSTALL_PREFIX=os.path.expanduser("~/.shadow")

OPENSSL_DEFAULT_VERSION="1.1.0h"
OPENSSL_URL="https://www.openssl.org/source/old/{0}/openssl-{1}.tar.gz".format(OPENSSL_DEFAULT_VERSION[:-1], OPENSSL_DEFAULT_VERSION)
OPENSSL_URL_SIG="https://www.openssl.org/source/old/{0}/openssl-{1}.tar.gz.asc".format(OPENSSL_DEFAULT_VERSION[:-1], OPENSSL_DEFAULT_VERSION)

LIBEVENT_DEFAULT_VERSION="2.1.11-stable"
LIBEVENT_URL="https://github.com/libevent/libevent/releases/download/release-{0}/libevent-{0}.tar.gz".format(LIBEVENT_DEFAULT_VERSION)
LIBEVENT_URL_SIG="https://github.com/libevent/libevent/releases/download/release-{0}/libevent-{0}.tar.gz.asc".format(LIBEVENT_DEFAULT_VERSION)

def main():
    parser_main = argparse.ArgumentParser(
        description='Utility to help setup the Shadow simulator plug-in that runs Tor',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    # setup our commands
    subparsers_main = parser_main.add_subparsers(
        help='run a subcommand (for help use <subcommand> --help)')

    # configure dependencies subcommand
    parser_dep = subparsers_main.add_parser('dependencies',
        help="configure and build custom plug-in dependencies",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_dep.set_defaults(func=dependencies,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    # add dependencies options
    parser_dep.add_argument('-p', '--prefix',
        help="configure PATH as dependency root installation directory",
        metavar="PATH",
        action="store", dest="prefix",
        default=INSTALL_PREFIX)

    parser_dep.add_argument('-y', '--assume-yes',
        help="don't ask for confirmation while downloading dependencies",
        action="store_true", dest="preapproved",
        default=False)

    # configure build subcommand
    parser_build = subparsers_main.add_parser('build',
        help='configure and build plug-in',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_build.set_defaults(func=build,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    # add building options
    parser_build.add_argument('-y', '--assume-yes',
        help="don't ask for confirmation while downloading dependencies",
        action="store_true", dest="preapproved",
        default=False)

    parser_build.add_argument('-p', '--prefix',
        help="configure PATH as Shadow root installation directory",
        metavar="PATH",
        action="store", dest="prefix",
        default=INSTALL_PREFIX)

    parser_build.add_argument('-i', '--include',
        help="append PATH to the list of paths searched for headers. useful if dependencies are installed to non-standard locations, or when compiling custom libraries.",
        metavar="PATH",
        action="append", dest="extra_includes",
        default=[INSTALL_PREFIX+ "/include", os.path.expanduser("~/.local/include"), os.path.expanduser("~/.local/share/llvm/cmake")])

    parser_build.add_argument('-l', '--library',
        help="append PATH to the list of paths searched for libraries. useful if dependencies are installed to non-standard locations, or when compiling custom libraries.",
        metavar="PATH",
        action="append", dest="extra_libraries",
        default=[INSTALL_PREFIX+ "/lib", os.path.expanduser("~/.local/lib")])

    parser_build.add_argument('-c', '--clean',
        help="force a full rebuild by removing build cache",
        action="store_true", dest="do_force_rebuild",
        default=False)

    parser_build.add_argument('-g', '--debug',
        help="build in extra memory checks and debugging symbols when running Shadow",
        action="store_true", dest="do_debug",
        default=False)

    parser_build.add_argument('-v', '--verbose',
        help="print verbose output from the compiler",
        action="store_true", dest="do_verbose",
        default=False)

    parser_build.add_argument('-j', '--jobs',
        help="number of jobs to run simultaneously during the build",
        metavar="N", type=int,
        action="store", dest="njobs",
        default=1)#multiprocessing.cpu_count())

    parser_build.add_argument('-o', '--profile',
        help="build in gprof profiling information when running Shadow",
        action="store_true", dest="do_profile",
        default=False)

    parser_build.add_argument('-t', '--test',
        help="build tests",
        action="store_true", dest="do_test",
        default=False)

    parser_build.add_argument('--enable-evp-cipher-encryption',
        help="do not intercept EVP_Cipher, so that we allow EVP_Cipher encryption to be performed as normal during simulation",
        action="store_true", dest="enable_evpcipher",
        default=False)

    parser_build.add_argument('--enable-torflow',
        help="Build a plugin that mimics the TorFlow relay measurement process.",
        action="store_true", dest="enable_torflow",
        default=False)

    # configure install subcommand
    parser_install = subparsers_main.add_parser('install', help='install Shadow',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser_install.set_defaults(func=install,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    # get arguments, accessible with args.value
    args = parser_main.parse_args()
    # run chosen command
    r = args.func(args)

    logging.info("returning code '{0}'".format(r))
    sys.exit(r)

def dependencies(args):
    if args.prefix is not None: args.prefix = getfullpath(args.prefix)
    filepath=getfullpath(__file__)
    rootdir=filepath[:filepath.rfind("/")]
    builddir=getfullpath(BUILD_PREFIX)

    keyring=getfullpath(rootdir + "/tools/deps_keyring.gpg")

    ## we will start in build directory
    if not os.path.exists(builddir): os.makedirs(builddir)
    os.chdir(builddir)

    openssl_tarball = get("./", OPENSSL_URL, OPENSSL_URL_SIG, keyring, args.preapproved)
    if openssl_tarball is None: return -1
    libevent_tarball = get("./", LIBEVENT_URL, LIBEVENT_URL_SIG, keyring, args.preapproved)
    if libevent_tarball is None: return -1

    ## build openssl first

    dir = extract(openssl_tarball)
    if dir is None: return -1
    os.chdir(dir)

    ## for debugging and profiling (you may want to enable -g and -pg independently)
    #configure = "./config --prefix={0} no-shared threads -fPIC -g -pg -DPURIFY -Bsymbolic".format(args.prefix)
    is64 = sys.maxsize > 2**32
    ecopt = "enable-ec_nistp_64_gcc_128" if is64 else ""
    configure = "./config --prefix={0} shared threads {1} -fPIC".format(args.prefix, ecopt)

    logging.info("now attempting to build openssl with '{0}'".format(configure))
    if automake(configure, "make", "make install_sw") != 0:
        logging.error("problems building {0}".format(openssl_tarball))
        return -1

    ## now build libevent

    os.chdir(builddir)
    dir = extract(libevent_tarball)
    if dir is None: return -1
    os.chdir(dir)

    #configure = "./configure --prefix={0} --enable-shared=no CFLAGS=\"-fPIC -I{0} -g -pg\" LDFLAGS=\"-L{0}\" CPPFLAGS=\"-DUSE_DEBUG\"".format(args.prefix)
    configure = "./configure --prefix={0} --enable-shared CFLAGS=\"-fPIC -I{0}/include/\" LDFLAGS=\"-L{0}/lib/\"".format(args.prefix)

    logging.info("now attempting to build libevent with '{0}'".format(configure))
    if automake(configure, "make", "make install") != 0:
        logging.error("problems building {0}".format(openssl_tarball))
        return -1

    logging.info("successfully installed dependencies to '{0}'".format(args.prefix))
    return 0

def automake(configure, make, install):
    retcode = subprocess.call(shlex.split(configure))
    if retcode != 0: return retcode
    retcode = subprocess.call(shlex.split(make))
    if retcode != 0: return retcode
    retcode = subprocess.call(shlex.split(install))
    if retcode != 0: return retcode
    return 0

def build(args):
    # get absolute paths
    if args.prefix is not None: args.prefix = getfullpath(args.prefix)

    filepath=getfullpath(__file__)
    rootdir=filepath[:filepath.rfind("/")]
    builddir=getfullpath(BUILD_PREFIX)
    installdir=getfullpath(args.prefix)

    args.keyring = getfullpath(rootdir + "/tools/deps_keyring.gpg")

    # clear cmake cache
    if args.do_force_rebuild and os.path.exists(builddir+"/main"): shutil.rmtree(builddir+"/main")

    # create directories
    if not os.path.exists(builddir+"/main"): os.makedirs(builddir+"/main")
    if not os.path.exists(installdir): os.makedirs(installdir)

    # build up args string for the cmake command
    cmake_cmd = "cmake " + rootdir + " -DCMAKE_INSTALL_PREFIX=" + installdir

    # other cmake options
    if args.do_verbose: os.putenv("VERBOSE", "1")
    if args.do_test: cmake_cmd += " -DSHADOW_TEST=ON"
    if args.do_profile: cmake_cmd += " -DSHADOW_PROFILE=ON"
    if args.enable_evpcipher: cmake_cmd += " -DSHADOW_ENABLE_EVPCIPHER=ON"
    if args.enable_torflow: cmake_cmd += " -DSHADOW_ENABLE_TORFLOW=ON"

    # we will run from build directory
    calledDirectory = os.getcwd()

    # run build tasks
    os.chdir(builddir)

    # now we will be using cmake to build shadow and the plug-ins
    os.chdir(builddir+"/main")

    # hack to make passing args to CMAKE work... doesnt seem to like the first arg
    args.extra_includes.insert(0, "./")
    args.extra_libraries.insert(0, "./")

    # add extra library and include directories as absolution paths
    make_paths_absolute(args.extra_includes)
    make_paths_absolute(args.extra_libraries)

    # make sure we can access them from cmake
    cmake_cmd += " -DCMAKE_EXTRA_INCLUDES="    + ';'.join(args.extra_includes)
    cmake_cmd += " -DCMAKE_EXTRA_LIBRARIES="   + ';'.join(args.extra_libraries)

    # call cmake to configure the make process, wait for completion
    logging.info("running \'{0}\' from \'{1}\'".format(cmake_cmd, os.getcwd()))
    retcode = subprocess.call(cmake_cmd.strip().split())
    logging.info("cmake returned " + str(retcode))

    if retcode == 0:
        # call make, wait for it to finish
        make = "make -j{0}".format(args.njobs)
        logging.info("calling " + make)
        retcode = subprocess.call(shlex.split(make))
        logging.info("make returned " + str(retcode))
        if retcode == 0: logging.info("now run \'./setup install\'")
        else: log("ERROR! Non-zero return code from make.")
    else: log("ERROR! Non-zero return code from cmake.")

    # go back to where we came from
    os.chdir(calledDirectory)
    return retcode

def install(args):
    builddir=getfullpath(BUILD_PREFIX+"/main")
    if not os.path.exists(builddir):
        log("ERROR: please build before installing!")
        return

    # go to build dir and install from makefile
    calledDirectory = os.getcwd()
    os.chdir(builddir)

    # call make install, wait for it to finish
    makeCommand = "make install"

    logging.info("calling \'"+makeCommand+"\'")
    retcode = subprocess.call(makeCommand.strip().split())
    logging.info("make install returned " + str(retcode))
    if retcode == 0: logging.info("Successfully installed shadow-plugin-tor!")

    # go back to where we came from
    os.chdir(calledDirectory)
    return retcode

def getfullpath(path):
    return os.path.abspath(os.path.expanduser(path))

def make_paths_absolute(list):
    for i in xrange(len(list)): list[i] = getfullpath(list[i])

def extract(tarball):
    if tarfile.is_tarfile(tarball):
        tar = tarfile.open(tarball, "r:gz")
        n = tar.next().name
        while n.find('/') < 0: n = tar.next().name
        d = getfullpath(os.getcwd() + "/" + n[:n.index('/')])
        #tar.extractall()
        subprocess.call(shlex.split("tar xaf {0}".format(tarball)))
        tar.close()
        return d
    else:
        logging.error("\'{0}\' is not a tarfile".format(tarball))
        return None

def get(targetdir, fileurl, sigurl, keyring, preapproved=False):
    targetfile = getfullpath(targetdir + "/" + os.path.basename(fileurl))
    targetsig = getfullpath(targetdir + "/" + os.path.basename(sigurl))

    if not os.path.exists(targetfile) and (download(fileurl, targetfile, preapproved) < 0): return None

    if preapproved: return targetfile

    if not query_yes_no("Do you want to check the signature of {0}?".format(os.path.basename(fileurl))): return targetfile

    if (not os.path.exists(targetsig)) and (download(sigurl, targetsig) < 0): return None

    question = "Do you want to use the included keyring instead of the running user's keyring?"
    answer = query_yes_no(question)
    retcode = -2
    gpg_binaries = ["gpg2", "gpg"]
    for gpg_binary in gpg_binaries:
        try:
            if answer:
                gpg = gpg_binary + " --keyring {0} --verify {1}".format(keyring, targetsig)
                logging.info("running \'{0}\'".format(gpg))
                retcode = subprocess.call(shlex.split(gpg))
            else:
                gpg = gpg_binary + " --verify {0}".format(targetsig)
                logging.info("running \'{0}\'".format(gpg))
                retcode = subprocess.call(shlex.split(gpg))
        except (OSError):
            logging.info(gpg_binary + " binary is not present")
            continue
        break
    success = False
    if retcode == 0:
        logging.info("Signature is good")
        success = True
    else:
        if retcode == -2:
            logging.warning("No GnuPG binary found")
        else:
            logging.warning("Signature is bad")
        if query_yes_no("Do you want to continue without verifying the signature?"): success = True

    if success and query_yes_no("Everything looks good. OK to proceed?"): return targetfile
    else: return None

def download(url, target_path, preapproved=False):
    if preapproved or query_yes_no("May we download \'{0}\'?".format(url)):
        logging.info("attempting to download " + url)
        try:
            u = urllib2.urlopen(url)
            localfile = open(target_path, 'w')
            localfile.write(u.read())
            localfile.close()
            logging.info("successfully downloaded \'{0}\' using urllib2".format(url))
            return 0
        except urllib2.URLError as e:
            logging.error("failed to download \'{0}\' using urllib2".format(url))
            curlpath = which("curl")
            if curlpath is not None:
                retcode = subprocess.call(shlex.split("{0} -f -L -O {1}".format(curlpath, url)))
                if retcode == 0:
                    logging.info("successfully downloaded \'{0}\' using curl".format(url))
                    return 0
            raise e
            return -1
    else:
        logging.error("user denied download permission.")
        return -1

def query_yes_no(question, default="yes"):
    """Ask a yes/no question via raw_input() and return their answer.

    "question" is a string that is presented to the user.
    "default" is the presumed answer if the user just hits <Enter>.
        It must be "yes" (the default), "no" or None (meaning
        an answer is required of the user).

    The "answer" return value is one of "yes" or "no".
    """
    valid = {"yes":True,   "y":True,  "ye":True, "no":False,     "n":False}
    if default == None: prompt = " [y/n] "
    elif default == "yes": prompt = " [Y/n] "
    elif default == "no": prompt = " [y/N] "
    else: raise ValueError("invalid default answer: '%s'" % default)

    color_start_code = "\033[1m" + "\033[93m" # <- bold+yellow
    color_end_code = "\033[0m"
    while True:
        sys.stdout.write(color_start_code + question + color_end_code + prompt)
        choice = raw_input().lower()
        if default is not None and choice == '': return valid[default]
        elif choice in valid: return valid[choice]
        else: sys.stdout.write("Please respond with 'yes' or 'no' (or 'y' or 'n').\n")

## helper - test if program is in path
def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)
    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return program
    else:
        for path in os.environ["PATH"].split(os.pathsep):
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return exe_file
    return None

def log(msg):
    color_start_code = "\033[94m" # red: \033[91m"
    color_end_code = "\033[0m"
    prefix = "[" + str(datetime.now()) + "] Shadow Setup: "
    print >> sys.stderr, color_start_code + prefix + msg + color_end_code

if __name__ == '__main__':
    main()
